name: CI
on: [push, pull_request]

jobs:
  build:
    name: Maven package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '17'
    - name: Maven package
      run: mvn package